### PR TITLE
Format code using 'cargo fmt'

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by wduquette** [comment]
Howdy!  Yes, I need to do this.  I'd prefer not to do it as an external pull-request, though, especially as I've done quite a lot of work since seeing this.

**Comment by wduquette** [comment]
Just ran cargo fmt, and pushed to master.

**Comment by Atul9** [comment]
@wduquette Is it that this project doesn't accept any pull-request?

**Comment by wduquette** [comment]
(Just saw this.)  I'm willing to accept pull-requests, judging them on a case-by-case basis.  In this case, I would have had to resolve a bunch of merge conflicts to merge your pull-request; it was *much* easier just to run `cargo fmt` myself.

If there's something you're particularly interested in doing, let me know.

**Pull request closed without merging**
